### ISSUE TITLE
Doesn't run on Windows

### ISSUE THREAD

**Issue by thecmdrunner** [thecmdrunner/remotion-gtts-template#2]
## The issue

`npm start` and `npm run build` product these errors when ran on Windows (not WSL).

![image](https://user-images.githubusercontent.com/38887390/233433627-b69f3efb-3314-4b24-9a72-fcc6515563b4.png)

![image](https://user-images.githubusercontent.com/38887390/233433440-f0e4cf49-5dfc-4e72-adad-9d8464742893.png)

## Possible fixes

Maybe backslashes don't work well on Windows?

https://www.reddit.com/r/learnjavascript/comments/zyq40q/help_spawn_enoent_errno_4058/

----

I hope we can fix this issue before v4 release, because [Windows support is very important](https://www.youtube.com/watch?v=jo_B4LTHi3I&t=74s) :)

**Comment by JonnyBurger** [comment]
Interesting, do you have the `npx` command at all?

**Comment by thecmdrunner** [comment]
Yes I do, and `npx remotion preview` does work just fine. No audio though, because audioserver doesn't launch that way.

![image](https://user-images.githubusercontent.com/38887390/233560190-c015226e-8928-4553-8953-85b631e82fd9.png)
